app: fw-api-app

service:
  name: foodwar-server

plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs10.x
  region: ap-northeast-2
  stage: 'dev'

functions:
  api:
    handler: src/server.handler
    events:
      - http:
          path: /
          method: any
      - http:
          path: /{any+}
          method: any
